name: hrm.hrm_act_v1@HierarchicalReasoningModel_ACTV1
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

# Balanced settings for both speed and accuracy
halt_exploration_prob: 0.1
halt_max_steps: 8  # Reduced from 16 but not too aggressive

H_cycles: 2  # Keep original cycles for learning capability
L_cycles: 2

H_layers: 4
L_layers: 4

hidden_size: 512
num_heads: 8
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope